use_frameworks!

platform :ios, '10.0'

target 'RMRMCommandPoolKit_Example' do
  pod 'RMRMCommandPoolKit', :path => '../'

  target 'RMRMCommandPoolKit_Tests' do
    inherit! :search_paths

    
  end
end
